version: "3.9"

services:
  mongo:
    image: mongo:7
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build:
      context: ./backend
    restart: unless-stopped
    env_file:
      - ./backend/.env
    environment:
      - MONGO_URI=mongodb://mongo:27017/vitacollab
    depends_on:
      - mongo
    ports:
      - "5000:5000"

  frontend:
    build:
      context: ./frontend
    restart: unless-stopped
    environment:
      - NEXT_PUBLIC_API_BASE_URL=http://localhost:5000/api/v1
    depends_on:
      - backend
    ports:
      - "3000:3000"

volumes:
  mongo_data:
